chrome_driver_path: "drivers/chromedriver-mac-arm64/chromedriver"

job_boards:
  - name: "JobsDB"
    search_url: "https://th.jobsdb.com/en"
    job_card_selector: "FILL_IN_JOB_CARD_SELECTOR"
    job_title_selector: "FILL_IN_JOB_TITLE_SELECTOR"
    job_company_selector: "FILL_IN_COMPANY_SELECTOR"
    job_link_selector: "FILL_IN_LINK_SELECTOR"

  - name: "Indeed"
    search_url: "https://www.indeed.com/jobs?q=python&l=Remote"
    job_card_selector: ".result"
    job_title_selector: ".jobtitle"
    job_company_selector: ".company"
    job_link_selector: "a.jobtitle"

  - name: "LinkedIn"
    search_url: "https://www.linkedin.com/jobs/search?keywords=python"
    job_card_selector: ".base-card"
    job_title_selector: ".base-search-card__title"
    job_company_selector: ".base-search-card__subtitle"
    job_link_selector: "a.base-card__full-link"

  - name: "104 (Taiwan)"
    search_url: "https://go.104.com.tw/expats/?utm_source=104&utm_medium=cweb_popup"
    job_card_selector: "FILL_IN_JOB_CARD_SELECTOR"
    job_title_selector: "FILL_IN_JOB_TITLE_SELECTOR"
    job_company_selector: "FILL_IN_COMPANY_SELECTOR"
    job_link_selector: "FILL_IN_LINK_SELECTOR"